=== Guarucano/Web-Master/Modulo 6 XML - Ajax/clase2/esquema/escuela2.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="escuela">
      <xs:complexType>
         <xs:sequence>
          <xs:element ref="alumno" minOccurs="0" maxOccurs="unbounded">
          </xs:element>
         </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="alumno">
      <xs:complexType>
        <xs:all>
          <xs:element name="numero_ID"></xs:element>
          <xs:element name="nombre"></xs:element>
          <xs:element name="apellido"></xs:element>
          <xs:element name="cedula"></xs:element>
          <xs:element name="telefono"></xs:element>
        </xs:all>
      </xs:complexType>
    </xs:element>

   
  </xs:schema>

=== Guarucano/Web-Master/Modulo 6 XML - Ajax/clase2/esquema/escuela2.xml
<?xml version="1.0" encoding ="UTF-8"?>
<?xml-stylesheet type="text/xsl"
 href="escuela2.xsl"?>
<escuela xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="escuela2.xsd">



	<alumno>
        <numero_ID>1232654</numero_ID>
    	<nombre>Miguel</nombre>
    	<apellido>Ordoñez</apellido>
    	<cedula>19546489</cedula>
    	<telefono>02625875854</telefono>
    </alumno>

    	<alumno>
        <numero_ID>123</numero_ID>
    	<nombre>Miguasdel</nombre>
    	<apellido>Ordasdoñez</apellido>
    	<cedula>19546123489</cedula>
    	<telefono>02612325875854</telefono>
    </alumno>

    <alumno>
        <numero_ID>No</numero_ID>
    	<nombre>Entiendo</nombre>
    	<apellido>Un</apellido>
    	<cedula>Coño</cedula>
    	<telefono>De la madre</telefono>
    </alumno>

</escuela>
