=== Guarucano/Web-Master/Modulo 6 XML - Ajax/clase2/esquema/nombres.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListaEmpleados">
      <xs:complexType>
         <xs:sequence>
          <xs:element ref="NombreEmpleado" minOccurs="0" maxOccurs="unbounded">
          </xs:element>
         </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="NombreEmpleado">
      <xs:complexType>
        <xs:all>
          <xs:element name="PrimerNombre"></xs:element>
          <xs:element name="SegundoNombre" minOccurs="0"></xs:element>
          <xs:element name="Apellido"></xs:element>
        </xs:all>
      </xs:complexType>
    </xs:element>
  </xs:schema>

=== Guarucano/Web-Master/Modulo 6 XML - Ajax/clase2/esquema/lista_de_nombres.xml
<?xml version="1.0" encoding="UTF-8"?>
<ListaEmpleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Nombres.xsd">
	<NombreEmpleado>
		<PrimerNombre>Rafael</PrimerNombre>
		<SegundoNombre>Jose</SegundoNombre>
		<Apellido>Carvajal</Apellido>
	</NombreEmpleado>
	<NombreEmpleado>
		<SegundoNombre>Saphina</SegundoNombre>
		<Apellido>Ramirez</Apellido>
		<PrimerNombre>Mary</PrimerNombre>
	</NombreEmpleado>
	<NombreEmpleado>
		<PrimerNombre>Robert</PrimerNombre>
		<Apellido>Contreras</Apellido>
	</NombreEmpleado>
</ListaEmpleados>
